agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_04_05

env:
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia --project=experiments/surface_fluxes_perfect_model -e 'using Pkg; Pkg.precompile()'
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.precompile()'


  - wait
  - label: "SurfaceFluxes perfect model calibration"
    command: julia --project=experiments/surface_fluxes_perfect_model test/caltech_hpc_e2e.jl
    artifact_paths: output/surface_fluxes_perfect_model/*
    
  - label: "Slurm job controller unit tests"
    command: julia --project=test test/slurm_unit_tests.jl
