agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_04_05

env:
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia --project=experiments/surface_fluxes_perfect_model -e 'using Pkg; Pkg.build("CalibrateAtmos"); Pkg.precompile()'

  - wait
  - label: "SurfaceFluxes perfect model calibration"
    command: julia --project=experiments/surface_fluxes_perfect_model test/slurm.jl
    artifact_paths: output/surface_fluxes_perfect_model/*
    agents:
      slurm_ntasks: 10
